### ISSUE TITLE
Noise black bars missing

### ISSUE THREAD

**Issue by metamn** [IliaIdakiev/eu-tyre-label-generator#1]
Thanks for the tool it is very handy :)

I'm wondering if the black bars for the noise can be added: http://www.etrma.org/uploads/images/Tyres/Tyre%20labelling%20information.jpg

**Comment by IliaIdakiev** [comment]
Sorry for the late response. I will add them :)

**Comment by dobromir-hristov** [comment]
Yep, this would be nice to have. Building a tire website and your script will come in handy. Only problem is responsiveness, but oh well.

**Comment by IliaIdakiev** [comment]
I added the noise markers and put some info in the README file how to handle different sizes. If someone finds the black markers with good quality and wants to change the current once send me a pull request.
